//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Video.Streaming
{
    using System;
    using System.Collections.Generic;
    
    public partial class VideoFile
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Title { get; set; }
        public string Key { get; set; }
        public string Description { get; set; }
        public Nullable<int> FileSize { get; set; }
        public string FilePath { get; set; }
    }
}
